### ISSUE TITLE
dplyr revdep checks: Variable context not set

### ISSUE THREAD

**Issue by lionel-** [PranaGeo/Spectral#72]
Hello,

I see in dplyr's revdep checks for the 0.6 release:

```r
[1] "Reading the NOMAD file /home/muelleki/git/R/dplyr/revdep/checks/geoSpectral.Rcheck/geoSpectral/test_data/nomad_seabass_v2.a_2008200.txt.gz off disk."
Error: Variable context not set
```

This is most likely caused by using `everything()` within an underscored SE variant like `select_()` or `mutate_each_()`.  An easy fix is to quote the call within a formula: `~everything()`.

**Comment by scizmeli** [comment]
Thanks lionel. this must have been fixed by now I guess. Closing.
